---
apiVersion: v1
kind: Service
metadata:
  name: jboss-service
  labels:
   author: intelliq
spec:
 type: NodePort
 ports:
   - targetPort: 8080
     port: 8080
     nodePort: 30008
 selector:
  type: webserver